version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies for frontend"
      - cd frontend
      - npm install
  build:
    commands:
      - echo "Building frontend"
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build

