version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: skillhub-frontend
    container_name: skillhub-frontend-container
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: skillhub-backend
    container_name: skillhub-backend-container
    ports:
      - '7000:7000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge