version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies for backend"
      - cd backend
      - npm install
  build:
    commands:
      - echo "Packaging backend"
artifacts:
  files:
    - '**/*'
  base-directory: backend

